# Generated by Django 5.0.6 on 2024-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=11)),
                ('ver_mas', models.TextField()),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
