# Generated by Django 5.0.6 on 2024-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_rename_nombre_apellido_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
        migrations.AddField(
            model_name='contacto',
            name='Contrasenia',
            field=models.CharField(default=1234567, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='Usuario',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
