# Generated by Django 5.0.6 on 2024-07-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_rename_email_contacto_email_remove_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
