# Generated by Django 5.0.6 on 2024-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_extra', '0002_rename_extradata_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
