# Generated by Django 5.0.6 on 2024-07-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_extra', '0003_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
